"""empty message

Revision ID: 0f61e9c009af
Revises: 2e307bac2a73
Create Date: 2018-03-06 13:36:56.640856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f61e9c009af'
down_revision = '2e307bac2a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.add_column('store_items', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_items', 'price')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=40), nullable=True),
    sa.Column('body', sa.VARCHAR(length=280), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
